### ISSUE TITLE
IfcDatasetReference should attribute ReferencedDataset be optional?

### ISSUE THREAD

**Issue by jmirtsch** [bSI-InfraRoom/IFC-Tunnel-Deployment#22]
https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/ifcdatasetreference.htm

WR1 suggests that attribute name should have a value if attribute ReferencedDataset is null, but the attribute is not optional.
Please advise.

**Comment by aothms** [comment]
The docs have the same issue:

> **Optional** dataset metadata can also be captured through reference to [IfcDatasetInformation](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/schema/ifcexternalreferenceresource/lexical/ifcdatasetinformation.htm)

[emphasis mine]

**Comment by SergejMuhic** [comment]
@jmirtsch I would agree. I think @larswik might just have forgotten to click the optional tick since we agreed to use `IfcDocumentInformation` as a template.

I will be regenerating the documentation once the schema builds. I had to correct a bunch of small issues that slipped through the reviews. 😄

**Comment by larswik** [comment]
Mistake noted. Fixing...

**Comment by pjanck** [comment]
Since https://github.com/bSI-InfraRoom/IFC-Specification/pull/501 was merged, I believe we can close this - what do you think @jmirtsch?
